//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f3)
//
//
// Ports:
// Name                         I/O  size props
// RDY_imem_server_request_put    O     1 reg
// imem_server_response_get       O   132 reg
// RDY_imem_server_response_get   O     1 reg
// RDY_dtmem_server_request_put   O     1 reg
// dtmem_server_response_get      O   132 reg
// RDY_dtmem_server_response_get  O     1 reg
// RDY_dmem_server_request_put    O     1 reg
// dmem_server_response_get       O   132 reg
// RDY_dmem_server_response_get   O     1 reg
// mem_client_request_get         O    64 reg
// RDY_mem_client_request_get     O     1 reg
// RDY_mem_client_response_put    O     1 reg
// RDY_dt_ptw_rsp_enq             O     1
// RDY_dt_ptw_flush               O     1 const
// RDY_dt_ptw_walk                O     1 const
// dt_ptw_count                   O     1
// RDY_dt_ptw_count               O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// imem_server_request_put        I   128 reg
// dtmem_server_request_put       I   128 reg
// dmem_server_request_put        I   128 reg
// mem_client_response_put        I    65 reg
// EN_imem_server_request_put     I     1
// EN_dtmem_server_request_put    I     1
// EN_dmem_server_request_put     I     1
// EN_mem_client_response_put     I     1
// EN_dt_ptw_rsp_enq              I     1
// EN_dt_ptw_flush                I     1
// EN_dt_ptw_walk                 I     1
// EN_imem_server_response_get    I     1
// EN_dtmem_server_response_get   I     1
// EN_dmem_server_response_get    I     1
// EN_mem_client_request_get      I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkPTW(CLK,
	     RST_N,

	     imem_server_request_put,
	     EN_imem_server_request_put,
	     RDY_imem_server_request_put,

	     EN_imem_server_response_get,
	     imem_server_response_get,
	     RDY_imem_server_response_get,

	     dtmem_server_request_put,
	     EN_dtmem_server_request_put,
	     RDY_dtmem_server_request_put,

	     EN_dtmem_server_response_get,
	     dtmem_server_response_get,
	     RDY_dtmem_server_response_get,

	     dmem_server_request_put,
	     EN_dmem_server_request_put,
	     RDY_dmem_server_request_put,

	     EN_dmem_server_response_get,
	     dmem_server_response_get,
	     RDY_dmem_server_response_get,

	     EN_mem_client_request_get,
	     mem_client_request_get,
	     RDY_mem_client_request_get,

	     mem_client_response_put,
	     EN_mem_client_response_put,
	     RDY_mem_client_response_put,

	     EN_dt_ptw_rsp_enq,
	     RDY_dt_ptw_rsp_enq,

	     EN_dt_ptw_flush,
	     RDY_dt_ptw_flush,

	     EN_dt_ptw_walk,
	     RDY_dt_ptw_walk,

	     dt_ptw_count,
	     RDY_dt_ptw_count);
  parameter [2 : 0] verbosity = 3'b0;
  input  CLK;
  input  RST_N;

  // action method imem_server_request_put
  input  [127 : 0] imem_server_request_put;
  input  EN_imem_server_request_put;
  output RDY_imem_server_request_put;

  // actionvalue method imem_server_response_get
  input  EN_imem_server_response_get;
  output [131 : 0] imem_server_response_get;
  output RDY_imem_server_response_get;

  // action method dtmem_server_request_put
  input  [127 : 0] dtmem_server_request_put;
  input  EN_dtmem_server_request_put;
  output RDY_dtmem_server_request_put;

  // actionvalue method dtmem_server_response_get
  input  EN_dtmem_server_response_get;
  output [131 : 0] dtmem_server_response_get;
  output RDY_dtmem_server_response_get;

  // action method dmem_server_request_put
  input  [127 : 0] dmem_server_request_put;
  input  EN_dmem_server_request_put;
  output RDY_dmem_server_request_put;

  // actionvalue method dmem_server_response_get
  input  EN_dmem_server_response_get;
  output [131 : 0] dmem_server_response_get;
  output RDY_dmem_server_response_get;

  // actionvalue method mem_client_request_get
  input  EN_mem_client_request_get;
  output [63 : 0] mem_client_request_get;
  output RDY_mem_client_request_get;

  // action method mem_client_response_put
  input  [64 : 0] mem_client_response_put;
  input  EN_mem_client_response_put;
  output RDY_mem_client_response_put;

  // action method dt_ptw_rsp_enq
  input  EN_dt_ptw_rsp_enq;
  output RDY_dt_ptw_rsp_enq;

  // action method dt_ptw_flush
  input  EN_dt_ptw_flush;
  output RDY_dt_ptw_flush;

  // action method dt_ptw_walk
  input  EN_dt_ptw_walk;
  output RDY_dt_ptw_walk;

  // value method dt_ptw_count
  output dt_ptw_count;
  output RDY_dt_ptw_count;

  // signals for module outputs
  wire [131 : 0] dmem_server_response_get,
		 dtmem_server_response_get,
		 imem_server_response_get;
  wire [63 : 0] mem_client_request_get;
  wire RDY_dmem_server_request_put,
       RDY_dmem_server_response_get,
       RDY_dt_ptw_count,
       RDY_dt_ptw_flush,
       RDY_dt_ptw_rsp_enq,
       RDY_dt_ptw_walk,
       RDY_dtmem_server_request_put,
       RDY_dtmem_server_response_get,
       RDY_imem_server_request_put,
       RDY_imem_server_response_get,
       RDY_mem_client_request_get,
       RDY_mem_client_response_put,
       dt_ptw_count;

  // register dt_ptw
  reg [1 : 0] dt_ptw;
  wire [1 : 0] dt_ptw$D_IN;
  wire dt_ptw$EN;

  // register dt_tlb
  reg dt_tlb;
  reg dt_tlb$D_IN;
  wire dt_tlb$EN;

  // register rg_pte_pa
  reg [63 : 0] rg_pte_pa;
  reg [63 : 0] rg_pte_pa$D_IN;
  wire rg_pte_pa$EN;

  // register rg_state
  reg [1 : 0] rg_state;
  reg [1 : 0] rg_state$D_IN;
  wire rg_state$EN;

  // ports of submodule f_dmem_imem_reqs
  reg [129 : 0] f_dmem_imem_reqs$D_IN;
  wire [129 : 0] f_dmem_imem_reqs$D_OUT;
  wire f_dmem_imem_reqs$CLR,
       f_dmem_imem_reqs$DEQ,
       f_dmem_imem_reqs$EMPTY_N,
       f_dmem_imem_reqs$ENQ,
       f_dmem_imem_reqs$FULL_N;

  // ports of submodule f_dmem_reqs
  wire [127 : 0] f_dmem_reqs$D_IN, f_dmem_reqs$D_OUT;
  wire f_dmem_reqs$CLR,
       f_dmem_reqs$DEQ,
       f_dmem_reqs$EMPTY_N,
       f_dmem_reqs$ENQ,
       f_dmem_reqs$FULL_N;

  // ports of submodule f_dmem_rsps
  reg [131 : 0] f_dmem_rsps$D_IN;
  wire [131 : 0] f_dmem_rsps$D_OUT;
  wire f_dmem_rsps$CLR,
       f_dmem_rsps$DEQ,
       f_dmem_rsps$EMPTY_N,
       f_dmem_rsps$ENQ,
       f_dmem_rsps$FULL_N;

  // ports of submodule f_dtmem_reqs
  wire [127 : 0] f_dtmem_reqs$D_IN, f_dtmem_reqs$D_OUT;
  wire f_dtmem_reqs$CLR,
       f_dtmem_reqs$DEQ,
       f_dtmem_reqs$EMPTY_N,
       f_dtmem_reqs$ENQ,
       f_dtmem_reqs$FULL_N;

  // ports of submodule f_dtmem_rsps
  reg [131 : 0] f_dtmem_rsps$D_IN;
  wire [131 : 0] f_dtmem_rsps$D_OUT;
  wire f_dtmem_rsps$CLR,
       f_dtmem_rsps$DEQ,
       f_dtmem_rsps$EMPTY_N,
       f_dtmem_rsps$ENQ,
       f_dtmem_rsps$FULL_N;

  // ports of submodule f_imem_reqs
  wire [127 : 0] f_imem_reqs$D_IN, f_imem_reqs$D_OUT;
  wire f_imem_reqs$CLR,
       f_imem_reqs$DEQ,
       f_imem_reqs$EMPTY_N,
       f_imem_reqs$ENQ,
       f_imem_reqs$FULL_N;

  // ports of submodule f_imem_rsps
  reg [131 : 0] f_imem_rsps$D_IN;
  wire [131 : 0] f_imem_rsps$D_OUT;
  wire f_imem_rsps$CLR,
       f_imem_rsps$DEQ,
       f_imem_rsps$EMPTY_N,
       f_imem_rsps$ENQ,
       f_imem_rsps$FULL_N;

  // ports of submodule f_mem_reqs
  reg [63 : 0] f_mem_reqs$D_IN;
  wire [63 : 0] f_mem_reqs$D_OUT;
  wire f_mem_reqs$CLR,
       f_mem_reqs$DEQ,
       f_mem_reqs$EMPTY_N,
       f_mem_reqs$ENQ,
       f_mem_reqs$FULL_N;

  // ports of submodule f_mem_rsps
  wire [64 : 0] f_mem_rsps$D_IN, f_mem_rsps$D_OUT;
  wire f_mem_rsps$CLR,
       f_mem_rsps$DEQ,
       f_mem_rsps$EMPTY_N,
       f_mem_rsps$ENQ,
       f_mem_rsps$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_merge_dmem_reqs,
       CAN_FIRE_RL_rl_merge_dtmem_reqs,
       CAN_FIRE_RL_rl_merge_imem_reqs,
       CAN_FIRE_RL_rl_ptw_level_0,
       CAN_FIRE_RL_rl_ptw_level_1,
       CAN_FIRE_RL_rl_ptw_level_2,
       CAN_FIRE_RL_rl_ptw_start,
       CAN_FIRE_dmem_server_request_put,
       CAN_FIRE_dmem_server_response_get,
       CAN_FIRE_dt_ptw_flush,
       CAN_FIRE_dt_ptw_rsp_enq,
       CAN_FIRE_dt_ptw_walk,
       CAN_FIRE_dtmem_server_request_put,
       CAN_FIRE_dtmem_server_response_get,
       CAN_FIRE_imem_server_request_put,
       CAN_FIRE_imem_server_response_get,
       CAN_FIRE_mem_client_request_get,
       CAN_FIRE_mem_client_response_put,
       WILL_FIRE_RL_rl_merge_dmem_reqs,
       WILL_FIRE_RL_rl_merge_dtmem_reqs,
       WILL_FIRE_RL_rl_merge_imem_reqs,
       WILL_FIRE_RL_rl_ptw_level_0,
       WILL_FIRE_RL_rl_ptw_level_1,
       WILL_FIRE_RL_rl_ptw_level_2,
       WILL_FIRE_RL_rl_ptw_start,
       WILL_FIRE_dmem_server_request_put,
       WILL_FIRE_dmem_server_response_get,
       WILL_FIRE_dt_ptw_flush,
       WILL_FIRE_dt_ptw_rsp_enq,
       WILL_FIRE_dt_ptw_walk,
       WILL_FIRE_dtmem_server_request_put,
       WILL_FIRE_dtmem_server_response_get,
       WILL_FIRE_imem_server_request_put,
       WILL_FIRE_imem_server_response_get,
       WILL_FIRE_mem_client_request_get,
       WILL_FIRE_mem_client_response_put;

  // inputs to muxes for submodule ports
  wire [131 : 0] MUX_f_dmem_rsps$enq_1__VAL_1,
		 MUX_f_dmem_rsps$enq_1__VAL_2,
		 MUX_f_dmem_rsps$enq_1__VAL_3,
		 MUX_f_dtmem_rsps$enq_1__VAL_4;
  wire [129 : 0] MUX_f_dmem_imem_reqs$enq_1__VAL_1,
		 MUX_f_dmem_imem_reqs$enq_1__VAL_2,
		 MUX_f_dmem_imem_reqs$enq_1__VAL_3;
  wire [1 : 0] MUX_rg_state$write_1__VAL_1, MUX_rg_state$write_1__VAL_2;
  wire MUX_dt_ptw$write_1__SEL_2,
       MUX_dt_ptw$write_1__SEL_3,
       MUX_dt_ptw$write_1__SEL_4,
       MUX_dt_tlb$write_1__SEL_1,
       MUX_dt_tlb$write_1__SEL_2,
       MUX_dt_tlb$write_1__SEL_3,
       MUX_f_dmem_rsps$enq_1__SEL_1,
       MUX_f_dmem_rsps$enq_1__SEL_2,
       MUX_f_dmem_rsps$enq_1__SEL_3,
       MUX_f_imem_rsps$enq_1__SEL_1,
       MUX_f_imem_rsps$enq_1__SEL_2,
       MUX_f_imem_rsps$enq_1__SEL_3,
       MUX_f_mem_reqs$enq_1__SEL_1,
       MUX_f_mem_reqs$enq_1__SEL_2,
       MUX_rg_state$write_1__SEL_1,
       MUX_rg_state$write_1__SEL_2,
       MUX_rg_state$write_1__SEL_3;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h1124;
  reg [31 : 0] v__h1402;
  reg [31 : 0] v__h1559;
  reg [31 : 0] v__h2023;
  reg [31 : 0] v__h3488;
  reg [31 : 0] v__h4878;
  reg [31 : 0] v__h1280;
  reg [31 : 0] v__h1113;
  reg [31 : 0] v__h1269;
  reg [31 : 0] v__h1391;
  reg [31 : 0] v__h1550;
  reg [31 : 0] v__h2014;
  reg [31 : 0] v__h3479;
  reg [31 : 0] v__h4869;
  // synopsys translate_on

  // remaining internal signals
  wire [63 : 0] lev_0_pte_pa__h3742,
		lev_1_PTN_pa__h2294,
		lev_1_pte_pa__h2296,
		lev_2_pte_pa__h1824,
		satp_pa__h1443,
		vpn_0_pa__h3741,
		vpn_1_pa__h2295,
		vpn_2_pa__h1823;
  wire [55 : 0] x__h1759, x__h2842;
  wire IF_NOT_f_mem_rsps_first__7_BIT_0_9_0_OR_NOT_f__ETC___d81,
       IF_NOT_f_mem_rsps_first__7_BIT_3_7_8_AND_NOT_f_ETC___d80,
       IF_f_dmem_imem_reqs_i_notEmpty__8_AND_f_dmem_i_ETC___d75,
       IF_f_mem_rsps_first__7_BIT_64_8_THEN_IF_NOT_f__ETC___d82,
       NOT_f_mem_rsps_first__7_BIT_0_9_0_OR_NOT_f_mem_ETC___d124,
       _dand1dt_ptw$EN_write,
       f_mem_rsps_first__7_BIT_64_8_AND_NOT_f_mem_rsp_ETC___d127,
       f_mem_rsps_first__7_BIT_64_8_AND_NOT_f_mem_rsp_ETC___d208;

  // action method imem_server_request_put
  assign RDY_imem_server_request_put = f_imem_reqs$FULL_N ;
  assign CAN_FIRE_imem_server_request_put = f_imem_reqs$FULL_N ;
  assign WILL_FIRE_imem_server_request_put = EN_imem_server_request_put ;

  // actionvalue method imem_server_response_get
  assign imem_server_response_get = f_imem_rsps$D_OUT ;
  assign RDY_imem_server_response_get = f_imem_rsps$EMPTY_N ;
  assign CAN_FIRE_imem_server_response_get = f_imem_rsps$EMPTY_N ;
  assign WILL_FIRE_imem_server_response_get = EN_imem_server_response_get ;

  // action method dtmem_server_request_put
  assign RDY_dtmem_server_request_put = f_dtmem_reqs$FULL_N ;
  assign CAN_FIRE_dtmem_server_request_put = f_dtmem_reqs$FULL_N ;
  assign WILL_FIRE_dtmem_server_request_put = EN_dtmem_server_request_put ;

  // actionvalue method dtmem_server_response_get
  assign dtmem_server_response_get = f_dtmem_rsps$D_OUT ;
  assign RDY_dtmem_server_response_get = f_dtmem_rsps$EMPTY_N ;
  assign CAN_FIRE_dtmem_server_response_get = f_dtmem_rsps$EMPTY_N ;
  assign WILL_FIRE_dtmem_server_response_get = EN_dtmem_server_response_get ;

  // action method dmem_server_request_put
  assign RDY_dmem_server_request_put = f_dmem_reqs$FULL_N ;
  assign CAN_FIRE_dmem_server_request_put = f_dmem_reqs$FULL_N ;
  assign WILL_FIRE_dmem_server_request_put = EN_dmem_server_request_put ;

  // actionvalue method dmem_server_response_get
  assign dmem_server_response_get = f_dmem_rsps$D_OUT ;
  assign RDY_dmem_server_response_get = f_dmem_rsps$EMPTY_N ;
  assign CAN_FIRE_dmem_server_response_get = f_dmem_rsps$EMPTY_N ;
  assign WILL_FIRE_dmem_server_response_get = EN_dmem_server_response_get ;

  // actionvalue method mem_client_request_get
  assign mem_client_request_get = f_mem_reqs$D_OUT ;
  assign RDY_mem_client_request_get = f_mem_reqs$EMPTY_N ;
  assign CAN_FIRE_mem_client_request_get = f_mem_reqs$EMPTY_N ;
  assign WILL_FIRE_mem_client_request_get = EN_mem_client_request_get ;

  // action method mem_client_response_put
  assign RDY_mem_client_response_put = f_mem_rsps$FULL_N ;
  assign CAN_FIRE_mem_client_response_put = f_mem_rsps$FULL_N ;
  assign WILL_FIRE_mem_client_response_put = EN_mem_client_response_put ;

  // action method dt_ptw_rsp_enq
  assign RDY_dt_ptw_rsp_enq =
	     f_dmem_imem_reqs$EMPTY_N && f_dtmem_rsps$FULL_N ;
  assign CAN_FIRE_dt_ptw_rsp_enq =
	     f_dmem_imem_reqs$EMPTY_N && f_dtmem_rsps$FULL_N ;
  assign WILL_FIRE_dt_ptw_rsp_enq = EN_dt_ptw_rsp_enq ;

  // action method dt_ptw_flush
  assign RDY_dt_ptw_flush = 1'd1 ;
  assign CAN_FIRE_dt_ptw_flush = 1'd1 ;
  assign WILL_FIRE_dt_ptw_flush = EN_dt_ptw_flush ;

  // action method dt_ptw_walk
  assign RDY_dt_ptw_walk = 1'd1 ;
  assign CAN_FIRE_dt_ptw_walk = 1'd1 ;
  assign WILL_FIRE_dt_ptw_walk = EN_dt_ptw_walk ;

  // value method dt_ptw_count
  assign dt_ptw_count = dt_ptw != 2'd0 ;
  assign RDY_dt_ptw_count = 1'd1 ;

  // submodule f_dmem_imem_reqs
  FIFO2 #(.width(32'd130), .guarded(1'd1)) f_dmem_imem_reqs(.RST(RST_N),
							    .CLK(CLK),
							    .D_IN(f_dmem_imem_reqs$D_IN),
							    .ENQ(f_dmem_imem_reqs$ENQ),
							    .DEQ(f_dmem_imem_reqs$DEQ),
							    .CLR(f_dmem_imem_reqs$CLR),
							    .D_OUT(f_dmem_imem_reqs$D_OUT),
							    .FULL_N(f_dmem_imem_reqs$FULL_N),
							    .EMPTY_N(f_dmem_imem_reqs$EMPTY_N));

  // submodule f_dmem_reqs
  FIFO2 #(.width(32'd128), .guarded(1'd1)) f_dmem_reqs(.RST(RST_N),
						       .CLK(CLK),
						       .D_IN(f_dmem_reqs$D_IN),
						       .ENQ(f_dmem_reqs$ENQ),
						       .DEQ(f_dmem_reqs$DEQ),
						       .CLR(f_dmem_reqs$CLR),
						       .D_OUT(f_dmem_reqs$D_OUT),
						       .FULL_N(f_dmem_reqs$FULL_N),
						       .EMPTY_N(f_dmem_reqs$EMPTY_N));

  // submodule f_dmem_rsps
  FIFO2 #(.width(32'd132), .guarded(1'd1)) f_dmem_rsps(.RST(RST_N),
						       .CLK(CLK),
						       .D_IN(f_dmem_rsps$D_IN),
						       .ENQ(f_dmem_rsps$ENQ),
						       .DEQ(f_dmem_rsps$DEQ),
						       .CLR(f_dmem_rsps$CLR),
						       .D_OUT(f_dmem_rsps$D_OUT),
						       .FULL_N(f_dmem_rsps$FULL_N),
						       .EMPTY_N(f_dmem_rsps$EMPTY_N));

  // submodule f_dtmem_reqs
  FIFO2 #(.width(32'd128), .guarded(1'd1)) f_dtmem_reqs(.RST(RST_N),
							.CLK(CLK),
							.D_IN(f_dtmem_reqs$D_IN),
							.ENQ(f_dtmem_reqs$ENQ),
							.DEQ(f_dtmem_reqs$DEQ),
							.CLR(f_dtmem_reqs$CLR),
							.D_OUT(f_dtmem_reqs$D_OUT),
							.FULL_N(f_dtmem_reqs$FULL_N),
							.EMPTY_N(f_dtmem_reqs$EMPTY_N));

  // submodule f_dtmem_rsps
  FIFO2 #(.width(32'd132), .guarded(1'd1)) f_dtmem_rsps(.RST(RST_N),
							.CLK(CLK),
							.D_IN(f_dtmem_rsps$D_IN),
							.ENQ(f_dtmem_rsps$ENQ),
							.DEQ(f_dtmem_rsps$DEQ),
							.CLR(f_dtmem_rsps$CLR),
							.D_OUT(f_dtmem_rsps$D_OUT),
							.FULL_N(f_dtmem_rsps$FULL_N),
							.EMPTY_N(f_dtmem_rsps$EMPTY_N));

  // submodule f_imem_reqs
  FIFO2 #(.width(32'd128), .guarded(1'd1)) f_imem_reqs(.RST(RST_N),
						       .CLK(CLK),
						       .D_IN(f_imem_reqs$D_IN),
						       .ENQ(f_imem_reqs$ENQ),
						       .DEQ(f_imem_reqs$DEQ),
						       .CLR(f_imem_reqs$CLR),
						       .D_OUT(f_imem_reqs$D_OUT),
						       .FULL_N(f_imem_reqs$FULL_N),
						       .EMPTY_N(f_imem_reqs$EMPTY_N));

  // submodule f_imem_rsps
  FIFO2 #(.width(32'd132), .guarded(1'd1)) f_imem_rsps(.RST(RST_N),
						       .CLK(CLK),
						       .D_IN(f_imem_rsps$D_IN),
						       .ENQ(f_imem_rsps$ENQ),
						       .DEQ(f_imem_rsps$DEQ),
						       .CLR(f_imem_rsps$CLR),
						       .D_OUT(f_imem_rsps$D_OUT),
						       .FULL_N(f_imem_rsps$FULL_N),
						       .EMPTY_N(f_imem_rsps$EMPTY_N));

  // submodule f_mem_reqs
  FIFO2 #(.width(32'd64), .guarded(1'd1)) f_mem_reqs(.RST(RST_N),
						     .CLK(CLK),
						     .D_IN(f_mem_reqs$D_IN),
						     .ENQ(f_mem_reqs$ENQ),
						     .DEQ(f_mem_reqs$DEQ),
						     .CLR(f_mem_reqs$CLR),
						     .D_OUT(f_mem_reqs$D_OUT),
						     .FULL_N(f_mem_reqs$FULL_N),
						     .EMPTY_N(f_mem_reqs$EMPTY_N));

  // submodule f_mem_rsps
  FIFO2 #(.width(32'd65), .guarded(1'd1)) f_mem_rsps(.RST(RST_N),
						     .CLK(CLK),
						     .D_IN(f_mem_rsps$D_IN),
						     .ENQ(f_mem_rsps$ENQ),
						     .DEQ(f_mem_rsps$DEQ),
						     .CLR(f_mem_rsps$CLR),
						     .D_OUT(f_mem_rsps$D_OUT),
						     .FULL_N(f_mem_rsps$FULL_N),
						     .EMPTY_N(f_mem_rsps$EMPTY_N));

  // rule RL_rl_merge_dmem_reqs
  assign CAN_FIRE_RL_rl_merge_dmem_reqs =
	     f_dmem_reqs$EMPTY_N && f_dmem_imem_reqs$FULL_N ;
  assign WILL_FIRE_RL_rl_merge_dmem_reqs =
	     CAN_FIRE_RL_rl_merge_dmem_reqs &&
	     !WILL_FIRE_RL_rl_merge_dtmem_reqs &&
	     !WILL_FIRE_RL_rl_merge_imem_reqs ;

  // rule RL_rl_merge_imem_reqs
  assign CAN_FIRE_RL_rl_merge_imem_reqs =
	     f_dmem_imem_reqs$FULL_N && f_imem_reqs$EMPTY_N ;
  assign WILL_FIRE_RL_rl_merge_imem_reqs = CAN_FIRE_RL_rl_merge_imem_reqs ;

  // rule RL_rl_ptw_start
  assign CAN_FIRE_RL_rl_ptw_start =
	     f_dmem_imem_reqs$EMPTY_N && f_mem_reqs$FULL_N &&
	     rg_state == 2'd0 &&
	     !dt_tlb ;
  assign WILL_FIRE_RL_rl_ptw_start = CAN_FIRE_RL_rl_ptw_start ;

  // rule RL_rl_ptw_level_2
  assign CAN_FIRE_RL_rl_ptw_level_2 =
	     f_dmem_imem_reqs$EMPTY_N && f_mem_rsps$EMPTY_N &&
	     IF_f_mem_rsps_first__7_BIT_64_8_THEN_IF_NOT_f__ETC___d82 &&
	     rg_state == 2'd1 ;
  assign WILL_FIRE_RL_rl_ptw_level_2 = MUX_rg_state$write_1__SEL_1 ;

  // rule RL_rl_ptw_level_1
  assign CAN_FIRE_RL_rl_ptw_level_1 =
	     f_dmem_imem_reqs$EMPTY_N && f_mem_rsps$EMPTY_N &&
	     IF_f_mem_rsps_first__7_BIT_64_8_THEN_IF_NOT_f__ETC___d82 &&
	     rg_state == 2'd2 ;
  assign WILL_FIRE_RL_rl_ptw_level_1 = MUX_rg_state$write_1__SEL_2 ;

  // rule RL_rl_ptw_level_0
  assign CAN_FIRE_RL_rl_ptw_level_0 =
	     f_dmem_imem_reqs$EMPTY_N && f_mem_rsps$EMPTY_N &&
	     (f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 ||
	      f_dmem_imem_reqs$D_OUT[129:128] == 2'd1 ||
	      f_imem_rsps$FULL_N) &&
	     IF_f_dmem_imem_reqs_i_notEmpty__8_AND_f_dmem_i_ETC___d75 &&
	     rg_state == 2'd3 ;
  assign WILL_FIRE_RL_rl_ptw_level_0 = MUX_rg_state$write_1__SEL_3 ;

  // rule RL_rl_merge_dtmem_reqs
  assign CAN_FIRE_RL_rl_merge_dtmem_reqs =
	     f_dmem_imem_reqs$FULL_N && f_dtmem_reqs$EMPTY_N ;
  assign WILL_FIRE_RL_rl_merge_dtmem_reqs =
	     CAN_FIRE_RL_rl_merge_dtmem_reqs &&
	     !WILL_FIRE_RL_rl_merge_imem_reqs ;

  // inputs to muxes for submodule ports
  assign MUX_dt_ptw$write_1__SEL_2 =
	     WILL_FIRE_RL_rl_ptw_level_0 &&
	     f_dmem_imem_reqs$D_OUT[129:128] == 2'd1 ;
  assign MUX_dt_ptw$write_1__SEL_3 =
	     WILL_FIRE_RL_rl_ptw_level_1 &&
	     (f_mem_rsps$D_OUT[64] &&
	      ((!f_mem_rsps$D_OUT[0] ||
		!f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] == 2'd1 ||
	       f_mem_rsps$D_OUT[0] &&
	       (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	       (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] == 2'd1) ||
	      !f_mem_rsps$D_OUT[64] &&
	      f_dmem_imem_reqs$D_OUT[129:128] == 2'd1) ;
  assign MUX_dt_ptw$write_1__SEL_4 =
	     WILL_FIRE_RL_rl_ptw_level_2 &&
	     (f_mem_rsps$D_OUT[64] &&
	      ((!f_mem_rsps$D_OUT[0] ||
		!f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] == 2'd1 ||
	       f_mem_rsps$D_OUT[0] &&
	       (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	       (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] == 2'd1) ||
	      !f_mem_rsps$D_OUT[64] &&
	      f_dmem_imem_reqs$D_OUT[129:128] == 2'd1) ;
  assign MUX_dt_tlb$write_1__SEL_1 =
	     WILL_FIRE_RL_rl_ptw_level_0 &&
	     f_mem_rsps_first__7_BIT_64_8_AND_NOT_f_mem_rsp_ETC___d208 ;
  assign MUX_dt_tlb$write_1__SEL_2 =
	     WILL_FIRE_RL_rl_ptw_level_1 &&
	     f_mem_rsps_first__7_BIT_64_8_AND_NOT_f_mem_rsp_ETC___d127 ;
  assign MUX_dt_tlb$write_1__SEL_3 =
	     WILL_FIRE_RL_rl_ptw_level_2 &&
	     f_mem_rsps_first__7_BIT_64_8_AND_NOT_f_mem_rsp_ETC___d127 ;
  assign MUX_f_dmem_rsps$enq_1__SEL_1 =
	     WILL_FIRE_RL_rl_ptw_level_2 &&
	     (f_mem_rsps$D_OUT[64] &&
	      ((!f_mem_rsps$D_OUT[0] ||
		!f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 ||
	       f_mem_rsps$D_OUT[0] &&
	       (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	       (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] == 2'd0) ||
	      !f_mem_rsps$D_OUT[64] &&
	      f_dmem_imem_reqs$D_OUT[129:128] == 2'd0) ;
  assign MUX_f_dmem_rsps$enq_1__SEL_2 =
	     WILL_FIRE_RL_rl_ptw_level_1 &&
	     (f_mem_rsps$D_OUT[64] &&
	      ((!f_mem_rsps$D_OUT[0] ||
		!f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 ||
	       f_mem_rsps$D_OUT[0] &&
	       (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	       (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] == 2'd0) ||
	      !f_mem_rsps$D_OUT[64] &&
	      f_dmem_imem_reqs$D_OUT[129:128] == 2'd0) ;
  assign MUX_f_dmem_rsps$enq_1__SEL_3 =
	     WILL_FIRE_RL_rl_ptw_level_0 &&
	     f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 ;
  assign MUX_f_imem_rsps$enq_1__SEL_1 =
	     WILL_FIRE_RL_rl_ptw_level_2 &&
	     (f_mem_rsps$D_OUT[64] &&
	      ((!f_mem_rsps$D_OUT[0] ||
		!f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] != 2'd0 &&
	       f_dmem_imem_reqs$D_OUT[129:128] != 2'd1 ||
	       f_mem_rsps$D_OUT[0] &&
	       (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	       (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] != 2'd0 &&
	       f_dmem_imem_reqs$D_OUT[129:128] != 2'd1) ||
	      !f_mem_rsps$D_OUT[64] &&
	      f_dmem_imem_reqs$D_OUT[129:128] != 2'd0 &&
	      f_dmem_imem_reqs$D_OUT[129:128] != 2'd1) ;
  assign MUX_f_imem_rsps$enq_1__SEL_2 =
	     WILL_FIRE_RL_rl_ptw_level_1 &&
	     (f_mem_rsps$D_OUT[64] &&
	      ((!f_mem_rsps$D_OUT[0] ||
		!f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] != 2'd0 &&
	       f_dmem_imem_reqs$D_OUT[129:128] != 2'd1 ||
	       f_mem_rsps$D_OUT[0] &&
	       (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	       (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] != 2'd0 &&
	       f_dmem_imem_reqs$D_OUT[129:128] != 2'd1) ||
	      !f_mem_rsps$D_OUT[64] &&
	      f_dmem_imem_reqs$D_OUT[129:128] != 2'd0 &&
	      f_dmem_imem_reqs$D_OUT[129:128] != 2'd1) ;
  assign MUX_f_imem_rsps$enq_1__SEL_3 =
	     WILL_FIRE_RL_rl_ptw_level_0 &&
	     f_dmem_imem_reqs$D_OUT[129:128] != 2'd0 &&
	     f_dmem_imem_reqs$D_OUT[129:128] != 2'd1 ;
  assign MUX_f_mem_reqs$enq_1__SEL_1 =
	     WILL_FIRE_RL_rl_ptw_level_2 && f_mem_rsps$D_OUT[64] &&
	     f_mem_rsps$D_OUT[0] &&
	     !f_mem_rsps$D_OUT[2] &&
	     !f_mem_rsps$D_OUT[3] &&
	     !f_mem_rsps$D_OUT[1] ;
  assign MUX_f_mem_reqs$enq_1__SEL_2 =
	     WILL_FIRE_RL_rl_ptw_level_1 && f_mem_rsps$D_OUT[64] &&
	     f_mem_rsps$D_OUT[0] &&
	     !f_mem_rsps$D_OUT[2] &&
	     !f_mem_rsps$D_OUT[3] &&
	     !f_mem_rsps$D_OUT[1] ;
  assign MUX_rg_state$write_1__SEL_1 =
	     CAN_FIRE_RL_rl_ptw_level_2 && !EN_dt_ptw_rsp_enq ;
  assign MUX_rg_state$write_1__SEL_2 =
	     CAN_FIRE_RL_rl_ptw_level_1 && !EN_dt_ptw_rsp_enq ;
  assign MUX_rg_state$write_1__SEL_3 =
	     CAN_FIRE_RL_rl_ptw_level_0 && !EN_dt_ptw_rsp_enq ;
  assign MUX_f_dmem_imem_reqs$enq_1__VAL_1 = { 2'd0, f_dmem_reqs$D_OUT } ;
  assign MUX_f_dmem_imem_reqs$enq_1__VAL_2 = { 2'd1, f_dtmem_reqs$D_OUT } ;
  assign MUX_f_dmem_imem_reqs$enq_1__VAL_3 = { 2'd2, f_imem_reqs$D_OUT } ;
  assign MUX_f_dmem_rsps$enq_1__VAL_1 =
	     { f_mem_rsps$D_OUT[64] ?
		 ((!f_mem_rsps$D_OUT[0] ||
		   !f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2] ||
		   f_mem_rsps$D_OUT[27:19] != 9'd0 ||
		   f_mem_rsps$D_OUT[18:10] != 9'd0) ?
		    2'd2 :
		    2'd0) :
		 2'd1,
	       f_mem_rsps$D_OUT[63:0],
	       2'd2,
	       rg_pte_pa } ;
  assign MUX_f_dmem_rsps$enq_1__VAL_2 =
	     { f_mem_rsps$D_OUT[64] ?
		 ((!f_mem_rsps$D_OUT[0] ||
		   !f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) ?
		    2'd2 :
		    ((f_mem_rsps$D_OUT[18:10] == 9'd0) ? 2'd0 : 2'd2)) :
		 2'd1,
	       f_mem_rsps$D_OUT[63:0],
	       2'd1,
	       rg_pte_pa } ;
  assign MUX_f_dmem_rsps$enq_1__VAL_3 =
	     { f_mem_rsps$D_OUT[64] ?
		 ((!f_mem_rsps$D_OUT[0] ||
		   !f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2] ||
		   !f_mem_rsps$D_OUT[3] && !f_mem_rsps$D_OUT[1]) ?
		    2'd2 :
		    2'd0) :
		 2'd1,
	       f_mem_rsps$D_OUT[63:0],
	       2'd0,
	       rg_pte_pa } ;
  assign MUX_f_dtmem_rsps$enq_1__VAL_4 =
	     { 68'hC0000000000000002, f_dmem_imem_reqs$D_OUT[127:64] } ;
  assign MUX_rg_state$write_1__VAL_1 =
	     f_mem_rsps$D_OUT[64] ?
	       ((!f_mem_rsps$D_OUT[0] ||
		 !f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) ?
		  2'd0 :
		  ((!f_mem_rsps$D_OUT[3] && !f_mem_rsps$D_OUT[1]) ?
		     2'd2 :
		     2'd0)) :
	       2'd0 ;
  assign MUX_rg_state$write_1__VAL_2 =
	     f_mem_rsps$D_OUT[64] ?
	       ((!f_mem_rsps$D_OUT[0] ||
		 !f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) ?
		  2'd0 :
		  ((!f_mem_rsps$D_OUT[3] && !f_mem_rsps$D_OUT[1]) ?
		     2'd3 :
		     2'd0)) :
	       2'd0 ;

  // register dt_ptw
  assign dt_ptw$D_IN = WILL_FIRE_RL_rl_merge_dtmem_reqs ? 2'd1 : 2'd0 ;
  assign dt_ptw$EN =
	     _dand1dt_ptw$EN_write ||
	     WILL_FIRE_RL_rl_ptw_level_0 &&
	     f_dmem_imem_reqs$D_OUT[129:128] == 2'd1 ||
	     EN_dt_ptw_rsp_enq ||
	     WILL_FIRE_RL_rl_merge_dtmem_reqs ;

  // register dt_tlb
  always@(MUX_dt_tlb$write_1__SEL_1 or
	  MUX_dt_tlb$write_1__SEL_2 or
	  MUX_dt_tlb$write_1__SEL_3 or
	  EN_dt_ptw_walk or EN_dt_ptw_flush or EN_dt_ptw_rsp_enq)
  case (1'b1)
    MUX_dt_tlb$write_1__SEL_1 || MUX_dt_tlb$write_1__SEL_2 ||
    MUX_dt_tlb$write_1__SEL_3:
	dt_tlb$D_IN = 1'd1;
    EN_dt_ptw_walk: dt_tlb$D_IN = 1'd0;
    EN_dt_ptw_flush: dt_tlb$D_IN = 1'd1;
    EN_dt_ptw_rsp_enq: dt_tlb$D_IN = 1'd0;
    default: dt_tlb$D_IN = 1'b0 /* unspecified value */ ;
  endcase
  assign dt_tlb$EN =
	     (WILL_FIRE_RL_rl_ptw_level_1 || WILL_FIRE_RL_rl_ptw_level_2) &&
	     f_mem_rsps_first__7_BIT_64_8_AND_NOT_f_mem_rsp_ETC___d127 ||
	     WILL_FIRE_RL_rl_ptw_level_0 &&
	     f_mem_rsps_first__7_BIT_64_8_AND_NOT_f_mem_rsp_ETC___d208 ||
	     EN_dt_ptw_walk ||
	     EN_dt_ptw_rsp_enq ||
	     EN_dt_ptw_flush ;

  // register rg_pte_pa
  always@(MUX_f_mem_reqs$enq_1__SEL_1 or
	  lev_1_pte_pa__h2296 or
	  MUX_f_mem_reqs$enq_1__SEL_2 or
	  lev_0_pte_pa__h3742 or
	  WILL_FIRE_RL_rl_ptw_start or lev_2_pte_pa__h1824)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_f_mem_reqs$enq_1__SEL_1: rg_pte_pa$D_IN = lev_1_pte_pa__h2296;
      MUX_f_mem_reqs$enq_1__SEL_2: rg_pte_pa$D_IN = lev_0_pte_pa__h3742;
      WILL_FIRE_RL_rl_ptw_start: rg_pte_pa$D_IN = lev_2_pte_pa__h1824;
      default: rg_pte_pa$D_IN = 64'hAAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign rg_pte_pa$EN =
	     WILL_FIRE_RL_rl_ptw_level_2 && f_mem_rsps$D_OUT[64] &&
	     f_mem_rsps$D_OUT[0] &&
	     !f_mem_rsps$D_OUT[2] &&
	     !f_mem_rsps$D_OUT[3] &&
	     !f_mem_rsps$D_OUT[1] ||
	     WILL_FIRE_RL_rl_ptw_level_1 && f_mem_rsps$D_OUT[64] &&
	     f_mem_rsps$D_OUT[0] &&
	     !f_mem_rsps$D_OUT[2] &&
	     !f_mem_rsps$D_OUT[3] &&
	     !f_mem_rsps$D_OUT[1] ||
	     WILL_FIRE_RL_rl_ptw_start ;

  // register rg_state
  always@(WILL_FIRE_RL_rl_ptw_level_2 or
	  MUX_rg_state$write_1__VAL_1 or
	  WILL_FIRE_RL_rl_ptw_level_1 or
	  MUX_rg_state$write_1__VAL_2 or
	  WILL_FIRE_RL_rl_ptw_level_0 or WILL_FIRE_RL_rl_ptw_start)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_rl_ptw_level_2:
	  rg_state$D_IN = MUX_rg_state$write_1__VAL_1;
      WILL_FIRE_RL_rl_ptw_level_1:
	  rg_state$D_IN = MUX_rg_state$write_1__VAL_2;
      WILL_FIRE_RL_rl_ptw_level_0: rg_state$D_IN = 2'd0;
      WILL_FIRE_RL_rl_ptw_start: rg_state$D_IN = 2'd1;
      default: rg_state$D_IN = 2'b10 /* unspecified value */ ;
    endcase
  end
  assign rg_state$EN =
	     WILL_FIRE_RL_rl_ptw_level_2 || WILL_FIRE_RL_rl_ptw_level_1 ||
	     WILL_FIRE_RL_rl_ptw_level_0 ||
	     WILL_FIRE_RL_rl_ptw_start ;

  // submodule f_dmem_imem_reqs
  always@(WILL_FIRE_RL_rl_merge_dmem_reqs or
	  MUX_f_dmem_imem_reqs$enq_1__VAL_1 or
	  WILL_FIRE_RL_rl_merge_dtmem_reqs or
	  MUX_f_dmem_imem_reqs$enq_1__VAL_2 or
	  WILL_FIRE_RL_rl_merge_imem_reqs or
	  MUX_f_dmem_imem_reqs$enq_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_rl_merge_dmem_reqs:
	  f_dmem_imem_reqs$D_IN = MUX_f_dmem_imem_reqs$enq_1__VAL_1;
      WILL_FIRE_RL_rl_merge_dtmem_reqs:
	  f_dmem_imem_reqs$D_IN = MUX_f_dmem_imem_reqs$enq_1__VAL_2;
      WILL_FIRE_RL_rl_merge_imem_reqs:
	  f_dmem_imem_reqs$D_IN = MUX_f_dmem_imem_reqs$enq_1__VAL_3;
      default: f_dmem_imem_reqs$D_IN =
		   130'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign f_dmem_imem_reqs$ENQ =
	     WILL_FIRE_RL_rl_merge_dmem_reqs ||
	     WILL_FIRE_RL_rl_merge_dtmem_reqs ||
	     WILL_FIRE_RL_rl_merge_imem_reqs ;
  assign f_dmem_imem_reqs$DEQ =
	     (WILL_FIRE_RL_rl_ptw_level_1 || WILL_FIRE_RL_rl_ptw_level_2) &&
	     (!f_mem_rsps$D_OUT[0] || f_mem_rsps$D_OUT[2] ||
	      f_mem_rsps$D_OUT[3] ||
	      f_mem_rsps$D_OUT[1] ||
	      !f_mem_rsps$D_OUT[64]) ||
	     WILL_FIRE_RL_rl_ptw_level_0 ||
	     EN_dt_ptw_rsp_enq ;
  assign f_dmem_imem_reqs$CLR = 1'b0 ;

  // submodule f_dmem_reqs
  assign f_dmem_reqs$D_IN = dmem_server_request_put ;
  assign f_dmem_reqs$ENQ = EN_dmem_server_request_put ;
  assign f_dmem_reqs$DEQ = WILL_FIRE_RL_rl_merge_dmem_reqs ;
  assign f_dmem_reqs$CLR = 1'b0 ;

  // submodule f_dmem_rsps
  always@(MUX_f_dmem_rsps$enq_1__SEL_1 or
	  MUX_f_dmem_rsps$enq_1__VAL_1 or
	  MUX_f_dmem_rsps$enq_1__SEL_2 or
	  MUX_f_dmem_rsps$enq_1__VAL_2 or
	  MUX_f_dmem_rsps$enq_1__SEL_3 or MUX_f_dmem_rsps$enq_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_f_dmem_rsps$enq_1__SEL_1:
	  f_dmem_rsps$D_IN = MUX_f_dmem_rsps$enq_1__VAL_1;
      MUX_f_dmem_rsps$enq_1__SEL_2:
	  f_dmem_rsps$D_IN = MUX_f_dmem_rsps$enq_1__VAL_2;
      MUX_f_dmem_rsps$enq_1__SEL_3:
	  f_dmem_rsps$D_IN = MUX_f_dmem_rsps$enq_1__VAL_3;
      default: f_dmem_rsps$D_IN =
		   132'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign f_dmem_rsps$ENQ =
	     MUX_f_dmem_rsps$enq_1__SEL_1 || MUX_f_dmem_rsps$enq_1__SEL_2 ||
	     WILL_FIRE_RL_rl_ptw_level_0 &&
	     f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 ;
  assign f_dmem_rsps$DEQ = EN_dmem_server_response_get ;
  assign f_dmem_rsps$CLR = 1'b0 ;

  // submodule f_dtmem_reqs
  assign f_dtmem_reqs$D_IN = dtmem_server_request_put ;
  assign f_dtmem_reqs$ENQ = EN_dtmem_server_request_put ;
  assign f_dtmem_reqs$DEQ = WILL_FIRE_RL_rl_merge_dtmem_reqs ;
  assign f_dtmem_reqs$CLR = 1'b0 ;

  // submodule f_dtmem_rsps
  always@(MUX_dt_ptw$write_1__SEL_4 or
	  MUX_f_dmem_rsps$enq_1__VAL_1 or
	  MUX_dt_ptw$write_1__SEL_3 or
	  MUX_f_dmem_rsps$enq_1__VAL_2 or
	  MUX_dt_ptw$write_1__SEL_2 or
	  MUX_f_dmem_rsps$enq_1__VAL_3 or
	  EN_dt_ptw_rsp_enq or MUX_f_dtmem_rsps$enq_1__VAL_4)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_dt_ptw$write_1__SEL_4:
	  f_dtmem_rsps$D_IN = MUX_f_dmem_rsps$enq_1__VAL_1;
      MUX_dt_ptw$write_1__SEL_3:
	  f_dtmem_rsps$D_IN = MUX_f_dmem_rsps$enq_1__VAL_2;
      MUX_dt_ptw$write_1__SEL_2:
	  f_dtmem_rsps$D_IN = MUX_f_dmem_rsps$enq_1__VAL_3;
      EN_dt_ptw_rsp_enq: f_dtmem_rsps$D_IN = MUX_f_dtmem_rsps$enq_1__VAL_4;
      default: f_dtmem_rsps$D_IN =
		   132'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign f_dtmem_rsps$ENQ =
	     MUX_dt_ptw$write_1__SEL_4 || MUX_dt_ptw$write_1__SEL_3 ||
	     WILL_FIRE_RL_rl_ptw_level_0 &&
	     f_dmem_imem_reqs$D_OUT[129:128] == 2'd1 ||
	     EN_dt_ptw_rsp_enq ;
  assign f_dtmem_rsps$DEQ = EN_dtmem_server_response_get ;
  assign f_dtmem_rsps$CLR = 1'b0 ;

  // submodule f_imem_reqs
  assign f_imem_reqs$D_IN = imem_server_request_put ;
  assign f_imem_reqs$ENQ = EN_imem_server_request_put ;
  assign f_imem_reqs$DEQ = CAN_FIRE_RL_rl_merge_imem_reqs ;
  assign f_imem_reqs$CLR = 1'b0 ;

  // submodule f_imem_rsps
  always@(MUX_f_imem_rsps$enq_1__SEL_1 or
	  MUX_f_dmem_rsps$enq_1__VAL_1 or
	  MUX_f_imem_rsps$enq_1__SEL_2 or
	  MUX_f_dmem_rsps$enq_1__VAL_2 or
	  MUX_f_imem_rsps$enq_1__SEL_3 or MUX_f_dmem_rsps$enq_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_f_imem_rsps$enq_1__SEL_1:
	  f_imem_rsps$D_IN = MUX_f_dmem_rsps$enq_1__VAL_1;
      MUX_f_imem_rsps$enq_1__SEL_2:
	  f_imem_rsps$D_IN = MUX_f_dmem_rsps$enq_1__VAL_2;
      MUX_f_imem_rsps$enq_1__SEL_3:
	  f_imem_rsps$D_IN = MUX_f_dmem_rsps$enq_1__VAL_3;
      default: f_imem_rsps$D_IN =
		   132'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign f_imem_rsps$ENQ =
	     MUX_f_imem_rsps$enq_1__SEL_1 || MUX_f_imem_rsps$enq_1__SEL_2 ||
	     WILL_FIRE_RL_rl_ptw_level_0 &&
	     f_dmem_imem_reqs$D_OUT[129:128] != 2'd0 &&
	     f_dmem_imem_reqs$D_OUT[129:128] != 2'd1 ;
  assign f_imem_rsps$DEQ = EN_imem_server_response_get ;
  assign f_imem_rsps$CLR = 1'b0 ;

  // submodule f_mem_reqs
  always@(MUX_f_mem_reqs$enq_1__SEL_1 or
	  lev_1_pte_pa__h2296 or
	  MUX_f_mem_reqs$enq_1__SEL_2 or
	  lev_0_pte_pa__h3742 or
	  WILL_FIRE_RL_rl_ptw_start or lev_2_pte_pa__h1824)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_f_mem_reqs$enq_1__SEL_1: f_mem_reqs$D_IN = lev_1_pte_pa__h2296;
      MUX_f_mem_reqs$enq_1__SEL_2: f_mem_reqs$D_IN = lev_0_pte_pa__h3742;
      WILL_FIRE_RL_rl_ptw_start: f_mem_reqs$D_IN = lev_2_pte_pa__h1824;
      default: f_mem_reqs$D_IN =
		   64'hAAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign f_mem_reqs$ENQ =
	     WILL_FIRE_RL_rl_ptw_level_2 && f_mem_rsps$D_OUT[64] &&
	     f_mem_rsps$D_OUT[0] &&
	     !f_mem_rsps$D_OUT[2] &&
	     !f_mem_rsps$D_OUT[3] &&
	     !f_mem_rsps$D_OUT[1] ||
	     WILL_FIRE_RL_rl_ptw_level_1 && f_mem_rsps$D_OUT[64] &&
	     f_mem_rsps$D_OUT[0] &&
	     !f_mem_rsps$D_OUT[2] &&
	     !f_mem_rsps$D_OUT[3] &&
	     !f_mem_rsps$D_OUT[1] ||
	     WILL_FIRE_RL_rl_ptw_start ;
  assign f_mem_reqs$DEQ = EN_mem_client_request_get ;
  assign f_mem_reqs$CLR = 1'b0 ;

  // submodule f_mem_rsps
  assign f_mem_rsps$D_IN = mem_client_response_put ;
  assign f_mem_rsps$ENQ = EN_mem_client_response_put ;
  assign f_mem_rsps$DEQ =
	     WILL_FIRE_RL_rl_ptw_level_0 || WILL_FIRE_RL_rl_ptw_level_1 ||
	     WILL_FIRE_RL_rl_ptw_level_2 ;
  assign f_mem_rsps$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_NOT_f_mem_rsps_first__7_BIT_0_9_0_OR_NOT_f__ETC___d81 =
	     (!f_mem_rsps$D_OUT[0] ||
	      !f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) ?
	       (f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 ||
		f_dmem_imem_reqs$D_OUT[129:128] == 2'd1 ||
		f_imem_rsps$FULL_N) &&
	       IF_f_dmem_imem_reqs_i_notEmpty__8_AND_f_dmem_i_ETC___d75 :
	       IF_NOT_f_mem_rsps_first__7_BIT_3_7_8_AND_NOT_f_ETC___d80 ;
  assign IF_NOT_f_mem_rsps_first__7_BIT_3_7_8_AND_NOT_f_ETC___d80 =
	     (!f_mem_rsps$D_OUT[3] && !f_mem_rsps$D_OUT[1]) ?
	       f_mem_reqs$FULL_N :
	       (f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 ||
		f_dmem_imem_reqs$D_OUT[129:128] == 2'd1 ||
		f_imem_rsps$FULL_N) &&
	       IF_f_dmem_imem_reqs_i_notEmpty__8_AND_f_dmem_i_ETC___d75 ;
  assign IF_f_dmem_imem_reqs_i_notEmpty__8_AND_f_dmem_i_ETC___d75 =
	     (f_dmem_imem_reqs$EMPTY_N &&
	      f_dmem_imem_reqs$D_OUT[129:128] == 2'd0) ?
	       f_dmem_rsps$FULL_N :
	       !f_dmem_imem_reqs$EMPTY_N ||
	       f_dmem_imem_reqs$D_OUT[129:128] != 2'd1 ||
	       f_dtmem_rsps$FULL_N ;
  assign IF_f_mem_rsps_first__7_BIT_64_8_THEN_IF_NOT_f__ETC___d82 =
	     f_mem_rsps$D_OUT[64] ?
	       IF_NOT_f_mem_rsps_first__7_BIT_0_9_0_OR_NOT_f__ETC___d81 :
	       (f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 ||
		f_dmem_imem_reqs$D_OUT[129:128] == 2'd1 ||
		f_imem_rsps$FULL_N) &&
	       IF_f_dmem_imem_reqs_i_notEmpty__8_AND_f_dmem_i_ETC___d75 ;
  assign NOT_f_mem_rsps_first__7_BIT_0_9_0_OR_NOT_f_mem_ETC___d124 =
	     (!f_mem_rsps$D_OUT[0] ||
	      !f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) &&
	     f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 &&
	     dt_ptw == 2'd1 ||
	     f_mem_rsps$D_OUT[0] &&
	     (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	     (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	     f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 &&
	     dt_ptw == 2'd1 ;
  assign _dand1dt_ptw$EN_write =
	     (WILL_FIRE_RL_rl_ptw_level_1 || WILL_FIRE_RL_rl_ptw_level_2) &&
	     (f_mem_rsps$D_OUT[64] &&
	      ((!f_mem_rsps$D_OUT[0] ||
		!f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] == 2'd1 ||
	       f_mem_rsps$D_OUT[0] &&
	       (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	       (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	       f_dmem_imem_reqs$D_OUT[129:128] == 2'd1) ||
	      !f_mem_rsps$D_OUT[64] &&
	      f_dmem_imem_reqs$D_OUT[129:128] == 2'd1) ;
  assign f_mem_rsps_first__7_BIT_64_8_AND_NOT_f_mem_rsp_ETC___d127 =
	     f_mem_rsps$D_OUT[64] &&
	     NOT_f_mem_rsps_first__7_BIT_0_9_0_OR_NOT_f_mem_ETC___d124 ||
	     !f_mem_rsps$D_OUT[64] &&
	     f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 &&
	     dt_ptw == 2'd1 ;
  assign f_mem_rsps_first__7_BIT_64_8_AND_NOT_f_mem_rsp_ETC___d208 =
	     f_mem_rsps$D_OUT[64] &&
	     f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 &&
	     dt_ptw == 2'd1 ||
	     !f_mem_rsps$D_OUT[64] &&
	     f_dmem_imem_reqs$D_OUT[129:128] == 2'd0 &&
	     dt_ptw == 2'd1 ;
  assign lev_0_pte_pa__h3742 = lev_1_PTN_pa__h2294 + vpn_0_pa__h3741 ;
  assign lev_1_PTN_pa__h2294 = { 8'd0, x__h2842 } ;
  assign lev_1_pte_pa__h2296 = lev_1_PTN_pa__h2294 + vpn_1_pa__h2295 ;
  assign lev_2_pte_pa__h1824 = satp_pa__h1443 + vpn_2_pa__h1823 ;
  assign satp_pa__h1443 = { 8'd0, x__h1759 } ;
  assign vpn_0_pa__h3741 = { 52'd0, f_dmem_imem_reqs$D_OUT[84:76], 3'd0 } ;
  assign vpn_1_pa__h2295 = { 52'd0, f_dmem_imem_reqs$D_OUT[93:85], 3'd0 } ;
  assign vpn_2_pa__h1823 = { 52'd0, f_dmem_imem_reqs$D_OUT[102:94], 3'd0 } ;
  assign x__h1759 = { f_dmem_imem_reqs$D_OUT[43:0], 12'b0 } ;
  assign x__h2842 = { f_mem_rsps$D_OUT[53:10], 12'b0 } ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        dt_ptw <= `BSV_ASSIGNMENT_DELAY 2'd0;
	dt_tlb <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_state <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (dt_ptw$EN) dt_ptw <= `BSV_ASSIGNMENT_DELAY dt_ptw$D_IN;
	if (dt_tlb$EN) dt_tlb <= `BSV_ASSIGNMENT_DELAY dt_tlb$D_IN;
	if (rg_state$EN) rg_state <= `BSV_ASSIGNMENT_DELAY rg_state$D_IN;
      end
    if (rg_pte_pa$EN) rg_pte_pa <= `BSV_ASSIGNMENT_DELAY rg_pte_pa$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    dt_ptw = 2'h2;
    dt_tlb = 1'h0;
    rg_pte_pa = 64'hAAAAAAAAAAAAAAAA;
    rg_state = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dmem_reqs && verbosity != 3'd0)
	begin
	  v__h1124 = $stime;
	  #0;
	end
    v__h1113 = v__h1124 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dmem_reqs && verbosity != 3'd0)
	$write("%0d: %m.rl_merge_dmem_reqs:\n    ", v__h1113);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dmem_reqs && verbosity != 3'd0)
	$write("PTW_Req { ", "va: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dmem_reqs && verbosity != 3'd0)
	$write("'h%h", f_dmem_reqs$D_OUT[127:64]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dmem_reqs && verbosity != 3'd0)
	$write(", ", "satp: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dmem_reqs && verbosity != 3'd0)
	$write("'h%h", f_dmem_reqs$D_OUT[63:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dmem_reqs && verbosity != 3'd0) $write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_imem_reqs && verbosity != 3'd0)
	begin
	  v__h1402 = $stime;
	  #0;
	end
    v__h1391 = v__h1402 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_imem_reqs && verbosity != 3'd0)
	$write("%0d: %m.rl_merge_imem_reqs:\n    ", v__h1391);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_imem_reqs && verbosity != 3'd0)
	$write("PTW_Req { ", "va: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_imem_reqs && verbosity != 3'd0)
	$write("'h%h", f_imem_reqs$D_OUT[127:64]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_imem_reqs && verbosity != 3'd0)
	$write(", ", "satp: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_imem_reqs && verbosity != 3'd0)
	$write("'h%h", f_imem_reqs$D_OUT[63:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_imem_reqs && verbosity != 3'd0) $write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_start && verbosity != 3'd0)
	begin
	  v__h1559 = $stime;
	  #0;
	end
    v__h1550 = v__h1559 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_start && verbosity != 3'd0)
	$display("%0d: %m.rl_ptw_start:", v__h1550);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_start && verbosity != 3'd0 &&
	  f_dmem_imem_reqs$D_OUT[129:128] == 2'd0)
	$write("    for D_Mem:");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_start && verbosity != 3'd0 &&
	  f_dmem_imem_reqs$D_OUT[129:128] == 2'd1)
	$write("    for DT_Mem:");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_start && verbosity != 3'd0 &&
	  f_dmem_imem_reqs$D_OUT[129:128] != 2'd0 &&
	  f_dmem_imem_reqs$D_OUT[129:128] != 2'd1)
	$write("    for I_Mem:");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_start && verbosity != 3'd0)
	$display(" satp_pa %0h  va %0h",
		 satp_pa__h1443,
		 f_dmem_imem_reqs$D_OUT[102:64]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_start && verbosity != 3'd0)
	$display("    Sv39/Sv48: mem_req level 2 PTE for PA %0h",
		 lev_2_pte_pa__h1824);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_2 && verbosity != 3'd0)
	begin
	  v__h2023 = $stime;
	  #0;
	end
    v__h2014 = v__h2023 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_2 && verbosity != 3'd0)
	$display("%0d: %m.rl_ptw_level_2:", v__h2014);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_2 && verbosity != 3'd0)
	$display("    satp_pa %0h  va %0h  pte_pa %0h",
		 satp_pa__h1443,
		 f_dmem_imem_reqs$D_OUT[102:64],
		 rg_pte_pa);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_2 && f_mem_rsps$D_OUT[64] &&
	  (!f_mem_rsps$D_OUT[0] ||
	   !f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) &&
	  verbosity != 3'd0)
	$display("    pte %0h: PAGE FAULT: invalid PTE",
		 f_mem_rsps$D_OUT[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_2 && f_mem_rsps$D_OUT[64] &&
	  f_mem_rsps$D_OUT[0] &&
	  !f_mem_rsps$D_OUT[2] &&
	  !f_mem_rsps$D_OUT[3] &&
	  !f_mem_rsps$D_OUT[1] &&
	  verbosity != 3'd0)
	$display("    pte %0h: continue to level 1: req addr %0h",
		 f_mem_rsps$D_OUT[63:0],
		 lev_1_pte_pa__h2296);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_2 && f_mem_rsps$D_OUT[64] &&
	  f_mem_rsps$D_OUT[0] &&
	  (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	  (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	  (f_mem_rsps$D_OUT[27:19] != 9'd0 ||
	   f_mem_rsps$D_OUT[18:10] != 9'd0) &&
	  verbosity != 3'd0)
	$display("    pte %0h (leaf->gigapage): PAGE FAULT: PPN[1]/PPN[0] not 0",
		 f_mem_rsps$D_OUT[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_2 && f_mem_rsps$D_OUT[64] &&
	  f_mem_rsps$D_OUT[0] &&
	  (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	  (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	  f_mem_rsps$D_OUT[27:19] == 9'd0 &&
	  f_mem_rsps$D_OUT[18:10] == 9'd0 &&
	  verbosity != 3'd0)
	$display("    pte %0h (leaf->gigapage). pa %0h",
		 f_mem_rsps$D_OUT[63:0],
		 lev_1_PTN_pa__h2294);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_2 && !f_mem_rsps$D_OUT[64] &&
	  verbosity != 3'd0)
	$display("    ACCESS FAULT: fabric response error");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_1 && verbosity != 3'd0)
	begin
	  v__h3488 = $stime;
	  #0;
	end
    v__h3479 = v__h3488 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_1 && verbosity != 3'd0)
	$display("%0d: %m.rl_ptw_level_1:", v__h3479);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_1 && verbosity != 3'd0)
	$display("    satp_pa %0h  va %0h  pte_pa %0h",
		 satp_pa__h1443,
		 f_dmem_imem_reqs$D_OUT[102:64],
		 rg_pte_pa);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_1 && f_mem_rsps$D_OUT[64] &&
	  (!f_mem_rsps$D_OUT[0] ||
	   !f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) &&
	  verbosity != 3'd0)
	$display("    pte %0h: PAGE FAULT: invalid PTE",
		 f_mem_rsps$D_OUT[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_1 && f_mem_rsps$D_OUT[64] &&
	  f_mem_rsps$D_OUT[0] &&
	  !f_mem_rsps$D_OUT[2] &&
	  !f_mem_rsps$D_OUT[3] &&
	  !f_mem_rsps$D_OUT[1] &&
	  verbosity != 3'd0)
	$display("    pte %0h: continue to level 0: req addr %0h",
		 f_mem_rsps$D_OUT[63:0],
		 lev_0_pte_pa__h3742);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_1 && f_mem_rsps$D_OUT[64] &&
	  f_mem_rsps$D_OUT[0] &&
	  (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	  (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	  f_mem_rsps$D_OUT[18:10] == 9'd0 &&
	  verbosity != 3'd0)
	$display("    pte %0h (leaf->megapage); pa %0h",
		 f_mem_rsps$D_OUT[63:0],
		 lev_1_PTN_pa__h2294);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_1 && f_mem_rsps$D_OUT[64] &&
	  f_mem_rsps$D_OUT[0] &&
	  (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	  (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	  f_mem_rsps$D_OUT[18:10] != 9'd0 &&
	  verbosity != 3'd0)
	$display("    pte %0h (leaf->megapage): PAGE FAULT: PPN [0] is not zero",
		 f_mem_rsps$D_OUT[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_1 && !f_mem_rsps$D_OUT[64] &&
	  verbosity != 3'd0)
	$display("    ACCESS FAULT: fabric response error");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_0 && verbosity != 3'd0)
	begin
	  v__h4878 = $stime;
	  #0;
	end
    v__h4869 = v__h4878 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_0 && verbosity != 3'd0)
	$display("%0d: %m.rl_ptw_level_0:", v__h4869);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_0 && verbosity != 3'd0)
	$display("    satp_pa %0h  va %0h  pte_pa %0h",
		 satp_pa__h1443,
		 f_dmem_imem_reqs$D_OUT[102:64],
		 rg_pte_pa);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_0 && f_mem_rsps$D_OUT[64] &&
	  (!f_mem_rsps$D_OUT[0] ||
	   !f_mem_rsps$D_OUT[1] && f_mem_rsps$D_OUT[2]) &&
	  verbosity != 3'd0)
	$display("    pte %0h: PAGE FAULT: invalid PTE",
		 f_mem_rsps$D_OUT[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_0 && f_mem_rsps$D_OUT[64] &&
	  f_mem_rsps$D_OUT[0] &&
	  !f_mem_rsps$D_OUT[2] &&
	  !f_mem_rsps$D_OUT[3] &&
	  !f_mem_rsps$D_OUT[1] &&
	  verbosity != 3'd0)
	$display("    pte %0h: PAGE FAULT: not a leaf PTE",
		 f_mem_rsps$D_OUT[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_0 && f_mem_rsps$D_OUT[64] &&
	  f_mem_rsps$D_OUT[0] &&
	  (f_mem_rsps$D_OUT[1] || !f_mem_rsps$D_OUT[2]) &&
	  (f_mem_rsps$D_OUT[3] || f_mem_rsps$D_OUT[1]) &&
	  verbosity != 3'd0)
	$display("    pte %0h: leaf PTE; pa %0h",
		 f_mem_rsps$D_OUT[63:0],
		 lev_1_PTN_pa__h2294);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_ptw_level_0 && !f_mem_rsps$D_OUT[64] &&
	  verbosity != 3'd0)
	$display("    ACCESS FAULT: fabric response error");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dtmem_reqs && verbosity != 3'd0)
	begin
	  v__h1280 = $stime;
	  #0;
	end
    v__h1269 = v__h1280 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dtmem_reqs && verbosity != 3'd0)
	$write("%0d: %m.rl_merge_dtmem_reqs:\n    ", v__h1269);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dtmem_reqs && verbosity != 3'd0)
	$write("PTW_Req { ", "va: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dtmem_reqs && verbosity != 3'd0)
	$write("'h%h", f_dtmem_reqs$D_OUT[127:64]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dtmem_reqs && verbosity != 3'd0)
	$write(", ", "satp: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dtmem_reqs && verbosity != 3'd0)
	$write("'h%h", f_dtmem_reqs$D_OUT[63:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_merge_dtmem_reqs && verbosity != 3'd0) $write("\n");
  end
  // synopsys translate_on
endmodule  // mkPTW

